---
 - name: epel
   yum:
     name: epel-release
     state: latest

 - name: add software packages
   yum:
     name:
       - "@Development tools"
       - vim	
       - openmpi
       - openmpi-devel
       - mpich
       - mpich-devel
       - ccache
       - clang
       - valgrind
       - wget
       - python36
       - python-virtualenv
       - python-nose
       - python-pip
       - which
     state: latest
 - name: upgrade pip and virtualenv
   shell: pip install --upgrade pip virtualenv
 - name: install gcovr
   shell: pip install gcovr
