---
 - name: Add NVIDIA Docker’s official GPG key
   apt_key:
     url: https://nvidia.github.io/nvidia-docker/gpgkey
     state: present

 - name: Add NVIDIA Docker APT repositories
   get_url:
     url:  "https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list"
     dest: /etc/apt/sources.list.d/nvidia-docker.list

 - name: install packages for nvidia docker
   apt:
     name: ['nvidia-docker2']
     state: latest
     update_cache: yes

 - name: update Docker daemon.json
   copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    force: yes

 - name: restart docker
   service:
     name: docker
     state: restarted
