---
 - name: add jenkins group
   group:
     name: jenkins
     gid: 114
 - name: create jenkins user
   user:
     name: jenkins
     uid: 108
     group: jenkins
     groups: docker
 - name: Add jenkins user authorized key
   authorized_key:
    user: jenkins
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"
